version: "2"
services:
  app:
    image: ptflp/yii2-basic-app:v3
    depends_on:
      - appdb
      - frontend
    container_name: app
    restart: always
    volumes:
      - ./app:/var/www/
    networks:
      - skynet
    environment:
      - VIRTUAL_HOST=ptflp.ru
  frontend:
    image: node:9
    container_name: frontend
    working_dir: /app
    volumes:
      - ./app/web:/app
    command: npm install
  appdb:
    image: mariadb
    container_name: appdb
    restart: always
    env_file:
      - ./mysql/mysql.env
    networks:
      - skynet
    volumes:
      - "appdb:/var/lib/mysql"
networks:
  skynet:
    external:
      name: skynet
volumes:
  appdb:
    external:
      name: appdb